default: &default
  # ==========================================
  # ===== Example Facebook Service Setup =====
  # ==========================================
  # facebook:
  #   verify_token: XXXFACEBOOK_VERIFY_TOKENXXX
  #   page_access_token: XXXFACEBOOK_ACCESS_TOKENXXX
  #   setup:
  #     greeting: # Greetings are broken up by locale
  #       - locale: default
  #         text: "Welcome to my Facebook Bot."
  #     get_started:
  #       payload: new_user
  #     persistent_menu:
  #       - locale: default
  #         composer_input_disabled: false
  #         call_to_actions:
  #         - type: payload
  #           text: Some Button
  #           payload: some_button
  #
  # ===========================================
  # ======== Example SMS Service Setup ========
  # ===========================================
   twilio:
     account_sid: <%= ENV.fetch('TWILIO_ACCOUNT_SID') %>
     auth_token: <%= ENV.fetch('TWILIO_AUTH_TOKEN') %>
     from_phone: <%= ENV.fetch('TWILIO_FROM_PHONE') %>

production:
  <<: *default
development:
  <<: *default
test:
  <<: *default
